# Generated by Django 3.2.24 on 2024-02-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='frienly_name',
            new_name='friendly_name',
        ),
    ]
